pullRequestOpened: >
  Thank your for raising your pull request.

  1. Please make sure you have followed our [CONTRIBUTING GUIDELINES](https://labex.wiki/). 
  2. Our robot will synchronize your content online later. Please complete the online test according to the requirements of [How to Test](https://www.labex.wiki/basic/how-to-test). 
  3. After passing the test, please add **Test Complete** to the Labels section. If you can't add Label, please comment that the test has been completed.

  We will review it as soon as possible.

  ---

  感谢你提出拉取请求 (PR)。

  1.请确保你遵循了我们的 [贡献指南](https://labex.wiki/)。
  2.我们的机器人稍后会将你的内容同步上线。请根据 [如何测试](https://www.labex.wiki/zh/basic/how-to-test) 的要求完成在线测试。
  3.通过测试后，请将 **Test Complete** 添加到 PR Label。如果你无法添加 Label，请评论说明测试已完成。

  我们将尽快审查它。

issuesAssigned: >
  Hi, welcome to the LabEx community. 

  1. Please use the materials provided in the Issues and follow the [CONTRIBUTING GUIDELINES](https://labex.wiki/) to implement the full Lab or Challenge.
  2. Please leave a comment in the Issue stating the expected completion time.
  
  你好，欢迎来到 LabEx 社区。
  
  1. 请基于 Issues 中提供的素材，遵循 [贡献指南](https://labex.wiki/)，将完整的 Lab 或 Challenge 实现。
  2. 请在 Issue 中留下一条评论，说明预计完成时间。