from typing import Dict, Any
import numpy as np
from calculate_purchase_totals import calculate_purchase_totals
from calculate_average_purchases import calculate_average_purchases
from calculate_revenue_totals import calculate_revenue_totals
from round_values import round_values


def customer_stats(transactions: np.ndarray) -> Dict[str, Any]:
    """
    Calculates statistics about customer transactions.

    Parameters
    ----------
    transactions : np.ndarray
        A 2D NumPy array of shape (num_customers, num_products) representing the number of purchases of each product by each customer.

    Returns
    -------
    Dict[str, Any]
        A dictionary containing the following keys and values:
            'total_purchases_by_customer': np.ndarray
                A 1D NumPy array of shape (num_customers,) containing the total number of purchases for each customer.
            'total_purchases_by_product': np.ndarray
                A 1D NumPy array of shape (num_products,) containing the total number of purchases for each product.
            'total_revenue_by_customer': np.ndarray
                A 1D NumPy array of shape (num_customers,) containing the total revenue generated by each customer.
            'total_revenue_by_product': np.ndarray
                A 1D NumPy array of shape (num_products,) containing the total revenue generated by each product.
            'average_purchases_per_customer': float
                The average number of purchases per customer.
            'average_purchases_per_product': float
                The average number of purchases per product.
    """
    num_customers, num_products = transactions.shape

    # Calculate the total number of purchases for each customer and product
    total_purchases_by_customer, total_purchases_by_product = calculate_purchase_totals(
        transactions=transactions
    )

    # Calculate the total revenue generated by each customer and product
    total_revenue_by_customer, total_revenue_by_product = calculate_revenue_totals(
        total_purchases_by_customer=total_purchases_by_customer,
        total_purchases_by_product=total_purchases_by_product,
        prices=10,
    )

    # Calculate the average number of purchases per customer and product
    average_purchases_per_customer = calculate_average_purchases(
        total_purchases=total_purchases_by_customer
    )
    average_purchases_per_product = calculate_average_purchases(
        total_purchases=total_purchases_by_product
    )

    # TODO: Round all values to 2 decimal places
    total_purchases_by_customer = round_values(total_purchases_by_customer, 2)
    total_purchases_by_product = round_values(total_purchases_by_product, 2)
    total_revenue_by_customer = round_values(total_revenue_by_customer, 2)
    total_revenue_by_product = round_values(total_revenue_by_product, 2)
    average_purchases_per_customer = round_values(average_purchases_per_customer, 2)
    average_purchases_per_product = round_values(average_purchases_per_product, 2)

    return {
        "total_purchases_by_customer": total_purchases_by_customer,
        "total_purchases_by_product": total_purchases_by_product,
        "total_revenue_by_customer": total_revenue_by_customer,
        "total_revenue_by_product": total_revenue_by_product,
        "average_purchases_per_customer": average_purchases_per_customer,
        "average_purchases_per_product": average_purchases_per_product,
    }
